### ISSUE TITLE
turn-{0,1,2,3}: update bootstrap service to `kitsune_p2p_bootstrap-0.3.0-dev.5`

### ISSUE THREAD

**Issue by steveej** [holochain/holochain-infra#108]
- [x] update rust package
- [x] deploy to turn-3 and test
- [x] deploy to turn-2 and test
- [x] deploy to turn-{0,1}
- [x] test turn-{0,1}

@neonphog should the hc-service-check from the same tag work for this?

**Comment by neonphog** [comment]
@steveej are these typos:

> - deploy to turn-0 and test
> - deploy to turn-{1,2,3} and test again

should they not be `boot-0` & `boot-{1,2,3}`?

**Comment by neonphog** [comment]
@steveej 

> should the hc-service-check from the same tag work for this?

hc-service-check exercises the "now" api, which is unaffected by this change. So you can use an earlier tag or this same tag, both will work on both the pre-fix server and the post-fix server.

**Comment by steveej** [comment]
@neonphog is there any tool i can use to verify the presence and absence of the bug in a running instance f the bootstrap server?

**Comment by steveej** [comment]
> should they not be `boot-0` & `boot-{1,2,3}`?

i was referring to the nixosConfigurations identifier in this repo. you can see in the example of [turn-3 it also has a kitsune-bootstrap service configured](https://github.com/holochain/holochain-infra/blob/b1f02c77547129651798bb61de3ad7afd6a9a61c/modules/flake-parts/nixosConfigurations.turn-3/configuration.nix#L101-L107). (reminder: i set these up to run all services on one common host with 3 distinct IPv4 addresses, one of them having the A entry `bootstrap-$N.(...)`)

**Comment by neonphog** [comment]
@steveej 

> is there any tool i can use to verify the presence and absence of the bug in a running instance f the bootstrap server?

Yes, you can use the [hc_demo_cli](https://github.com/holochain/holochain/blob/develop/crates/hc_demo_cli/src/demo.rs#L13-L26)

**Comment by steveej** [comment]
> Yes, you can use the [hc_demo_cli](https://github.com/holochain/holochain/blob/develop/crates/hc_demo_cli/src/demo.rs#L13-L26)

running the `hc_demo_cli` main entrypoint also creates bogus entries on the bootstrap server, do i understand that correctly?

double-checking because you expressed concerns in the other issue:

> I don't know that I agree with this. hc_check_services was meant as a smoke test, not a comprehensive functionality tester that, in this case, would spam the bootstrap server with bogus entries...

_Originally posted by @neonphog in https://github.com/holochain/holochain/issues/3965#issuecomment-2147797102_
            
---

adding to the above, i did a manual test against turn-2 -- which isn't updated yet -- and it worked fine against my expectations, including a file transfer.

```
$ cargo run --bin hc-demo-cli -- gen-dna-file --output - | cargo run --bin hc-demo-cli -- run --bootstrap-url https://bootstrap-2.infra.holochain.org --signal-url wss://signal-2.infra.holochain.org
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on build directory
Finished dev [unoptimized + debuginfo] target(s) in 0.97s
 Running `target/debug/hc-demo-cli gen-dna-file --output -`
Finished dev [unoptimized + debuginfo] target(s) in 1.12s
 Running `target/debug/hc-demo-cli run --bootstrap-url 'https://bootstrap-2.infra.holochain.org' --signal-url 'wss://signal-2.infra.holochain.org'`
#DNA_HASH#uhC0kGfwr1MUrtM80WPPykNFTUpdJqp8iGpSzklbKqNvHeKVde1ax#
#AGENT_KEY#uhCAkjSoL9dkG6W4m1SQZqHEHioHB-4RKikLbuuHaYCK72ZyYxSfV#
#PUBLISHED#message1.txt#
#FETCHED#"hc-demo-cli-inbox/uhCkkiLY4OTYp2l-GRkxWrPvo-tn8TA3H-y0ezrFQge_qAp9QjkeY/message1.txt"#
```

:arrow_right:  i'm still looking for a way to verify the presence of this bug via any means on the CLI.

**Comment by neonphog** [comment]
@steveej - I was only suggesting that as part of a manual one-off verification. We should certainly *not* use hc_demo_cli as part of any automation.

**Comment by steveej** [comment]
giving an update here as well.

i reproduced the issue wich hc-demo-cli on holochain rev 96e00d2ee64647e68a43bb8c67f5e8d1a35a7e3f:

```
$ cat ../dna | env RUST_LOG=holochain=trace cargo run --bin hc-demo-cli -- run --bootstrap-url https://bootstrap-0.infra.holochain.org --signal-url wss://sbd-0.main.infra.holo.host 2>&1 | rg BadDecode
-06-05T20:06:53.187974Z ERROR enable_app{app_id="hc_demo_cli"}:process_app_status_fx:reconcile_cell_status_with_app_status:create_and_add_initialized_cells_for_running_apps: holochain::conductor::conductor::app_status_impls: crates/holochain/src/conductor/conductor.rs:2109: Network join failed for Cell(uhC0kVkzkuFZ6aYrZW3lbRHZAq0JbaLRMxY1WdFv2BcTSOfbH-paU, uhCAkoba0pBQSpxUH-OtON-CH0fDCJb73mG7TBGrAlhDaRsZEm_RT). This should never happen. Error: OtherKitsuneP2pError(Bootstrap(Bootstrap("Unhandled rejection: BadDecode(\"Custom { kind: Other, error: Syntax(\\\"missing field `dht_storage_arc_half_length`\\\") }\")")))
```

after the bootstrap server update the error went away. 2/4 of the machines have been updated so far.

**Comment by steveej** [comment]
updated and tested all bootstrap servers. note that the test with `hc-demo-cli` wasn't fully functional because of an issue in the tx5 client ([this PR integrates a fix](https://github.com/holochain/holochain/pull/3984)), however i verified that agent entries get created in the bootstrap server.
