### ISSUE TITLE
Production SBD Server

### ISSUE THREAD

**Issue by neonphog** [holochain/holochain-infra#96]
We need a running production SBD Server: [Repo](https://github.com/holochain/sbd/tree/main/rust/sbd-server) | [Crates.io](https://crates.io/crates/sbd-server)

- tls should be configured via `--cert-pem-file` and `--priv-key-pem-file`
  - note: the directory watching tls reload story has not yet been implemented. when tls certs are updated, the service must be restarted
- a decision must be made on whether this server should be guarded/proxied by cloudflare or not. If so, the cloudflare trusted ip must be configured via `--trusted-ip-header` setting.
- `--bind` must be called on the public interface, i.e. `--bind my.public.ip.address:443`
- all other settings / limits can be left as defaults
- can be tested with check-services tool on the [sbd integration branch](https://github.com/holochain/holochain/pull/3842)

**Comment by steveej** [comment]
i'm running into issues with SSL.

*(the rest of this comment is moved to https://github.com/holochain/sbd/issues/25)*
